### ISSUE TITLE
Element screenshot option

### ISSUE THREAD

**Issue by suntong** [Runjuu/page2image#12]
Puppeteer also provides capability to do screenshot for a specific element -- https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlescreenshotoptions

Can page2image currently do that? 
Hope it can someday. Thx.

**Comment by Runjuu** [comment]
Sounds great, I will add this feature soon

**Comment by Runjuu** [comment]
@suntong 
The latest version(v2.0.1) now support `selector` props for taking screenshot of element
