### ISSUE TITLE
Specify output location?

### ISSUE THREAD

**Issue by arunsathiya** [Runjuu/page2image#15]
Thank you for this package. Is it possible to specify the output location (folder on the computer) for the screenshots?

Apologies if Github issues is not the right choice for asking a support question. I see only a link to the Github issues page on [your package site](https://www.npmjs.com/package/page2image) for questions.

**Comment by runjuu** [comment]
[Here](https://github.com/Runjuu/page2image#path-default-using-current-path) is the specific  section of README. 🍻
