### ISSUE TITLE
How to solve "Chromium revision is not downloaded." ?

### ISSUE THREAD

**Issue by fiht** [Runjuu/page2image#2]
隔行如隔山，请 repo 主指教
操作系统：macOS Sierra
之前的操作是：
```
brew install node
npm install page2img
```
请问还需要何种后续操作才能跑起来？ （应该是需要下载 chrome headless，但是不知道如何和 page2img 联动起来），报错如下图：
![image](https://user-images.githubusercontent.com/15059493/29803897-7733e534-8cb1-11e7-8d4c-730c36e41ee2.png)

**Comment by Runjuu** [comment]
if you want to use page2image as [CLI command](https://github.com/Runjuu/page2image#using-by-cli-️), you should install package globally
```bash
npm i page2image -g
```

**Comment by Runjuu** [comment]
![image](https://user-images.githubusercontent.com/12002941/29804119-07e8f92e-8cb3-11e7-86a4-3f8f67822cd4.png)
have you been seeing a download prompt in your installation process?

**Comment by fiht** [comment]
Still not working... npm do not download chromium 
![image](https://user-images.githubusercontent.com/15059493/29808514-01c70ac8-8ccb-11e7-8a89-5e6502612807.png)

**Comment by Runjuu** [comment]
hmm 🤔...what is your Node.js & npm version?
```bash
node -v
npm -v
```

**Comment by fiht** [comment]
```
➜  ~ node -v
v8.1.4
➜  ~ npm -v
5.0.3
```

**Comment by Runjuu** [comment]
it's quite strange, i using same version to install page2images, it seems there is no problem with download chromium, perhaps you could uninstall it first and try to reinstall again.
![image](https://user-images.githubusercontent.com/12002941/29974072-54e01e52-8f64-11e7-8944-330c5deaf289.png)

also, you could try run below command to install it manually
```bash
cd /usr/local/lib/node_modules/page2image/ && npm install
```
